services:
  - type: web
    name: mlops-generator-backend
    runtime: python
    buildCommand: poetry install --no-dev
    startCommand: python api.py
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /api/options
