services:
  - type: web
    name: mlops-generator-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /api/options
